# Generated by Django 5.2.1 on 2025-05-27 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('launchDate', models.DateField()),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MinValueValidator(10.0)])),
                ('numberOfVotes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('language', models.CharField(default='?', max_length=20)),
                ('rating', models.CharField(choices=[('G', 'General Public'), ('PG', 'Parental Guidance Suggested'), ('R', 'Restricted')], max_length=2)),
                ('country', models.CharField(max_length=35)),
                ('director', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MinValueValidator(10.0)])),
                ('reviewText', models.TextField(max_length=500)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.movie')),
            ],
        ),
    ]
