# Generated by Django 5.2.1 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('launchDate', models.DateField()),
                ('score', models.FloatField(default=0.0)),
                ('rating', models.CharField(choices=[('G', 'General Public'), ('PG', 'Parental Guidance Suggested'), ('R', 'Restricted')])),
                ('country', models.CharField(max_length=35)),
                ('director', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
