# Generated by Django 5.2.1 on 2025-05-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='?', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'General Public'), ('PG', 'Parental Guidance Suggested'), ('R', 'Restricted')], max_length=2),
        ),
    ]
